### ISSUE TITLE
year(), month() and day() must be const

### ISSUE THREAD

**Issue by pascalc** [joacar/cprog11_lab2#2]
`Date::year()`, `Date::month()` and `Date::day()` must be const.

This means that we probably have to remove our wonderful caching idea and refresh the cache every time the timestamp is changed.

**Comment by joacar** [comment]
Crap.. Hopefully we can find time saving otherwise, if that is going to be
a problem. Weird with kattis time as well..

Sorry for not keeping in touch over the weekend. Had a whole day with my
girl-friend Saturday and Sunday I was at a "konfirmation" all day and
Friday can't even remember.. Gonna work today after work so I'll give you a
holla at Gmail or Skype or whatever!

Vnliga hlsningar / Regards
Joakim Carselind

WebFish Development
www.webfish.se

2011/10/30 pascalc <
reply@reply.github.com>
